# CICD workflow for python flask website

name: CICD-Pipeline-ElasticBeanstalk

env:
  S3-BUCKET-PATH  : "python-app-artifacts/sample-python-flask-website-artifacts"
  EB-APP-NAME     : "eb-python-flask-website"
  EB-ENV-NAME     : "Ebpythonflaskwebsite-env"
  ARTIFACT-NAME   : "app-artifact.zip"
  AWS-REGION      : "us-east-1"


on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: create deployment artifacts
        run:  |
              pwd
              zip -r ${{ env.ARTIFACT-NAME }} ./ -x *.git*

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.NAVSHA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.NAVSHA_AWS_SECRET_ACCESS_KEY }}
          aws-region            : ${{ env.AWS-REGION }}

      - name: upload artifacts to s3 bucket
        run: aws s3 cp ${{ env.ARTIFACT-NAME }} s3://{{ env.S3-BUCKET-PATH }}/

      - name: print message
        run: echo "End of CI Pipeline"


