# CICD workflow for python flask website

name: CD-Pipeline-Flask-Website

env:
  S3-BUCKET-NAME  : "python-app-artifacts"
  S3-BUCKET-PATH  : "sample-python-flask-website-artifacts"
  EB-APP-NAME     : "eb-python-flask-website"
  EB-ENV-NAME     : "Ebpythonflaskwebsite-env"
  ARTIFACT-NAME   : "app-artifact.zip"
  AWS-REGION      : "us-east-1"


on:
  push:
    branches:
      - master

jobs:

  build-pipeline:

    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: create deployment artifacts
        run:  |
              pwd
              zip -r ${{ env.ARTIFACT-NAME }} ./ -x *.git*

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.NAVSHA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.NAVSHA_AWS_SECRET_ACCESS_KEY }}
          aws-region            : ${{ env.AWS-REGION }}

      - name: upload artifacts to s3 bucket
        run: aws s3 cp ${{ env.ARTIFACT-NAME }} s3://${{ env.S3-BUCKET-NAME }}/${{ env.S3-BUCKET-PATH }}/

      - name: print message
        run:  echo "End of Build Pipeline"
  
  deploy-to-ElasticBeanstalk:

    runs-on: ubuntu-latest
    needs:  [build]

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.NAVSHA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.NAVSHA_AWS_SECRET_ACCESS_KEY }}
          aws-region            : ${{ env.AWS-REGION }}

      - name: create new ElasticBeanstalk version
        run:  |
              aws elasticbeanstalk create-application-version \
              --application-name ${{ env.EB-APP-NAME }} \
              --source-bundle S3Bucket="${{ env.S3-BUCKET-NAME }}",S3Key="${{ env.S3-BUCKET-PATH }}/${{ env.ARTIFACT-NAME }}" \
              --version-label "ver-${{ github.sha }}" \
              --description "commitSHA-${{ github.sha }}"

      - name: deploy new app version
        run:  |
              aws elasticbeanstalk update-environment \
              --environment-name ${{ env.EB-ENV-NAME }} \
              --version-label "ver-${{ github.sha }}"

      - name: print message
        run:  echo "End of ElasticBeanstalk Deploy Pipeline"

  deploy-to-EC2-Instance:

    runs-on: ubuntu-latest
    needs:  [build]

    steps:
      - name: print message
        run:  echo "End of EC2 Deploy Pipeline"